version: '2'
services:
  db:
    image: postgres:9.6
    ports:
      - '5432:5432'
    volumes:
      - 'db:/var/lib/postgresql/data'
  redis:
    image: 'redis:3.2-alpine'
    command: redis-server
    ports:
      - '6379-6379'
    volumes:
      - 'redis:/var/lib/redis/data'
  server:
    build: .
    command: bash start.sh
    volumes:
      - '.:/enemgo'
    volumes_from:
      - gems
    ports:
      - '3000:3000'
      - '8080:8080'
    depends_on:
      - db
      - redis
  jobs:
    build: .
    command: bash start_sidekiq.sh
    volumes:
      - '.:/enemgo'
    volumes_from:
      - gems
    depends_on:
      - server
      - db
      - redis
  whenever:
    build: .
    volumes:
      - '.:/enemgo'
      - './backups:/root/backups/'
    depends_on:
      - db
  gems:
    image: busybox
    volumes:
      - /enemgo_gems
volumes:
  db:
  redis:
